package healthApp.controller;

import java.io.IOException;
import java.util.ArrayList;

import healthApp.data.WorkoutBackPainDB;
import healthApp.model.WorkoutAnklePain;
import healthApp.model.WorkoutBackPain;
import healthApp.model.healthApp;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class BackPainController {
	@FXML
	private Button BirdDogBP;
	@FXML
	private Button LowerBackStretchBP;
	@FXML
	private Button BridgingBP;
	@FXML
	private Button loadCust;
	@FXML
	private Button Physio;
	@FXML
	private Button Programs;
    @FXML
    private ImageView backBtn;
    @FXML
    private ImageView locationBtn;
    @FXML
	private ImageView reminderBtn;
	@FXML
	private ImageView exerciseBtn;
	@FXML
	private ImageView homeBtn;
	@FXML
	private ImageView foodBtn;
	@FXML
	private ImageView socialBtn;
   
	private Scene myScene;
	   @FXML
	    void goBack(MouseEvent event) throws IOException {

	    	FXMLLoader loader=new FXMLLoader();
			loader.setLocation((getClass().getResource("/healthApp/view/CustConditionSelection.fxml")));
			 myScene=(Scene)((Node)event.getSource()).getScene();
			 Stage stage=(Stage)(myScene).getWindow();
			 Parent nextView=loader.load();
			 stage.setScene(new Scene(nextView));
			 stage.show();
	    }
    
	@FXML
	public void goLocation(MouseEvent event) throws IOException {

		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	// Event Listener on ImageView[#reminderBtn].onMouseClicked
	@FXML
	public void goReminder(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	// Event Listener on ImageView[#exerciseBtn].onMouseClicked
	@FXML
	public void goExercise(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	// Event Listener on ImageView[#homeBtn].onMouseClicked
	@FXML
	public void goHome(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/HomepageView.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	// Event Listener on ImageView[#foodBtn].onMouseClicked
	@FXML
	public void goFood(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	// Event Listener on ImageView[#socialBtn].onMouseClicked
	@FXML
	public void goSocial(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	
	WorkoutBackPain WBP = new WorkoutBackPain();
	WorkoutBackPainDB WBPDB = new WorkoutBackPainDB();	
	

	ArrayList<WorkoutBackPain> Exercises = WBPDB.getAllBackExercises();
	private ArrayList<String> BackPainlist = new ArrayList<String>();
	
	
	
	// Event Listener on Button[#BirdDogBP].onMouseClicked
	@FXML
	public void loadCust(ActionEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/CustConditionSelection.fxml")));
		Scene myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	
	
	@FXML
	public void addBirdDog(MouseEvent event) {
		 BackPainlist.add("Bird Dog");
		
	}
	// Event Listener on Button[#LowerBackStretchBP].onMouseClicked
	@FXML
	public void addBackStretch(MouseEvent event) {
		 BackPainlist.add("Back Stretch");
	}
	// Event Listener on Button[#BridgingBP].onMouseClicked
	@FXML
	public void addBridging(MouseEvent event) {
		 BackPainlist.add("Bridging");
	}
	
	@FXML
	public void addBackExercises(MouseEvent event) throws IOException {
		
         WorkoutBackPain Backdata = new WorkoutBackPain();
         ArrayList <String> BackList = Backdata.getBacklist();
       
         Backdata.setID("BackPain1");
         BackList = BackPainlist;
         Backdata.setBackPainList(BackList);
         WBPDB.addBackExerciseX(Backdata);
       
         System.out.print(Backdata);
         
         

		//AnkleExercise.goCustomisedWorkout();

	}
}
