package healthApp.controller;

import java.io.IOException;
import java.net.URL;
import java.time.format.DateTimeFormatter;
import java.util.ResourceBundle;

import healthApp.model.Event;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class EventController implements Initializable{
	@FXML
	private AnchorPane imageViewParent;
	@FXML
	private Text eName;
	@FXML
	private Text eDateTime;
	@FXML
	private Text eVenue;
	@FXML
	private Text eDescription;
	@FXML
	private ImageView mainPage;
	@FXML
	private ImageView homePage;
	@FXML
	private ImageView eImage;
	@FXML
	private Label eLabel;
	
	private Event chosenEvent;
	DateTimeFormatter customFormatter = DateTimeFormatter.ofPattern("d MMM yyyy, h:mm a");
	
	public void toHomepage(MouseEvent event) {
		try {
			Parent homePageLoader = FXMLLoader.load(getClass().getResource("/healthApp/view/HomepageView.fxml"));
			Scene homePageScene = new Scene(homePageLoader);
		
			Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
			window.setScene(homePageScene);
			window.show();
		}
		
		catch(IOException e) {
		}
	}
	
	public void toMainPage(MouseEvent event) {
		// TODO Autogenerated
		try {
			Parent mainPageLoader = FXMLLoader.load(getClass().getResource("/healthApp/view/SocialFunctionView.fxml"));
			Scene mainPageScene = new Scene(mainPageLoader);
		
			Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
			window.setScene(mainPageScene);
			window.show();
		}
		
		catch(IOException e) {
		}
	}
	
	public void toLocationPage(MouseEvent event) {
		try {
			Parent locationPageLoader = FXMLLoader.load(getClass().getResource("/healthApp/view/LocationView.fxml"));
			Scene locationPageScene = new Scene(locationPageLoader);
		
			Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
			window.setScene(locationPageScene);
			window.show();
		}
		
		catch(IOException e) {
		}
	}
	
	public void toEventList(MouseEvent event) {
		try {
			Parent locationPageLoader = FXMLLoader.load(getClass().getResource("/healthApp/view/EventListView.fxml"));
			Scene locationPageScene = new Scene(locationPageLoader);
		
			Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
			window.setScene(locationPageScene);
			window.show();
		}
		
		catch(IOException e) {
		}
	}
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		chosenEvent = EventListController.getButtonEvent();
		
		if(chosenEvent.getCategory().equals("Community Work")) {
			eLabel.setText("Community");
		}
		else if(chosenEvent.getCategory().equals("Information & Technology")) {
			eLabel.setText("Technology");
		}
		else {
			eLabel.setText(chosenEvent.getCategory());
		}
		
		Image eImg = new Image(chosenEvent.getImagePath());
		eImage.setImage(eImg);
		
		eName.setText(chosenEvent.getName());
		eDateTime.setText(chosenEvent.getEventDateTime().format(customFormatter).toString());
		eVenue.setText(chosenEvent.getVenue());
		eDescription.setWrappingWidth(320);
		eDescription.setText(chosenEvent.getDescription());
	}

}
