package healthApp.controller;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import healthApp.data.FoodDB;
import healthApp.model.Food;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;


public class filteredMeatController implements Initializable{
	@FXML
	private Button viewMeat;
	
	@FXML
	private ImageView chicken;
	@FXML
	private ImageView fish;
	@FXML
	private ImageView pork;
	@FXML
	private ImageView beef;

	private Scene myScene;
	FoodDB foodDatabase = new FoodDB();
	

	  @FXML
	  private ImageView backBtn;
		private ImageView locationBtn;
		@FXML
		private ImageView reminderBtn;
		@FXML
		private ImageView exerciseBtn;
		@FXML
		private ImageView homeBtn;
		@FXML
		private ImageView foodBtn;
		@FXML
		private ImageView socialBtn;
	   

  @FXML
  void goBack(MouseEvent event) throws IOException {
  	FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
  }

  @FXML
		public void goLocation(MouseEvent event) throws IOException {

				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#reminderBtn].onMouseClicked
			@FXML
			public void goReminder(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#exerciseBtn].onMouseClicked
			@FXML
			public void goExercise(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#homeBtn].onMouseClicked
			@FXML
			public void goHome(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/HomepageView.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#foodBtn].onMouseClicked
			@FXML
			public void goFood(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#socialBtn].onMouseClicked
			@FXML
			public void goSocial(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			
	// Event Listener on Button[#viewMeat].onMouseClicked
	@FXML
	public void viewMeat(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("MEAT")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);
		fSRC.setSearchResult("Meat");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Meat");


	}	
	// Event Listener on ImageView[#chicken].onMouseClicked
	@FXML
	public void filterChicken(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("Chicken")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);
		fSRC.setSearchResult("Chicken");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Chicken");


	}
	// Event Listener on ImageView[#fish].onMouseClicked
	@FXML
	public void filterFish(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("Fish")) {
				meatCategory.add(hasMeat.getName());
			}
		}	
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Fish");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Fish");

	}
	// Event Listener on ImageView[#pork].onMouseClicked
	@FXML
	public void filterPork(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("Pork")) {
				meatCategory.add(hasMeat.getName());
			}
		}	
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);
		fSRC.setSearchResult("Pork");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Pork");

		}
	// Event Listener on ImageView[#beef].onMouseClicked
	@FXML
	public void filterBeef(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("Beef")) {
				meatCategory.add(hasMeat.getName());
			}
		}	
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Beef");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Beef");

		}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		viewMeat.setStyle("-fx-border-color: #17202A; -fx-border-width: 3px;-fx-background-color:pink;");
		
	}
}
