package healthApp.controller;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import healthApp.data.FoodDB;
import healthApp.model.Food;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;


public class filteredFruitsAndVegetablesController implements Initializable{
	@FXML
	private Button viewFruitsAndVegetables;
	@FXML
	private ImageView berries;
	@FXML
	private ImageView citrusFruit;
	@FXML
	private ImageView rootVegetables;
	@FXML
	private ImageView herbageVegetables;
	


	private Scene myScene;
	
	FoodDB foodDatabase = new FoodDB();
	
	
	  @FXML
	  private ImageView backBtn;
		private ImageView locationBtn;
		@FXML
		private ImageView reminderBtn;
		@FXML
		private ImageView exerciseBtn;
		@FXML
		private ImageView homeBtn;
		@FXML
		private ImageView foodBtn;
		@FXML
		private ImageView socialBtn;
	   

    @FXML
    void goBack(MouseEvent event) throws IOException {
    	FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
    }

    @FXML
		public void goLocation(MouseEvent event) throws IOException {

				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#reminderBtn].onMouseClicked
			@FXML
			public void goReminder(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#exerciseBtn].onMouseClicked
			@FXML
			public void goExercise(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#homeBtn].onMouseClicked
			@FXML
			public void goHome(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/HomepageView.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#foodBtn].onMouseClicked
			@FXML
			public void goFood(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#socialBtn].onMouseClicked
			@FXML
			public void goSocial(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			
		
	// Event Listener on Button[#viewFruitsAndVegetables].onMouseClicked
	@FXML
	public void viewFruitsAndVegetables(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			
			if (hasMeat.getCategory().contains("FRUITSANDVEGETABLES")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);		
		fSRC.setSearchResult("Fruits and vegetables");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Fruits and vegetables");

	}
	// Event Listener on ImageView[#berries].onMouseClicked
	@FXML
	public void filterBerries(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("Berries")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Berries");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Berries");
}
	// Event Listener on ImageView[#citrusFruit].onMouseClicked
	@FXML
	public void filterCitrusFruit(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("CitrusFruit")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Citrus fruit");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Citrus fruit");
}
	// Event Listener on ImageView[#rootVegetables].onMouseClicked
	@FXML
	public void filterRootVegetables(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("RootVegetables")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Root vegetables");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Root vegetables");
}
	// Event Listener on ImageView[#herbageVegetables].onMouseClicked
	@FXML
	public void filterHerbageVegetables(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("HerbageVegetables")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Herbage vegetables");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Herbage vegetables");
}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		viewFruitsAndVegetables.setStyle("-fx-border-color: #17202A; -fx-border-width: 3px;-fx-background-color:pink;");
		
	}
}
