package healthApp.controller;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import application.Main;
import healthApp.data.FoodDB;
import healthApp.model.Food;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;


public class filteredMilkController implements Initializable{
	@FXML
	private ImageView wholeMilk;
	@FXML
	private ImageView iceCream;
	@FXML
	private ImageView cheese;
	@FXML
	private Button viewMilk;
	
	
	private Scene myScene;
	FoodDB foodDatabase = new FoodDB();
	  @FXML
	  private ImageView backBtn;
		private ImageView locationBtn;
		@FXML
		private ImageView reminderBtn;
		@FXML
		private ImageView exerciseBtn;
		@FXML
		private ImageView homeBtn;
		@FXML
		private ImageView foodBtn;
		@FXML
		private ImageView socialBtn;
	   

  @FXML
  void goBack(MouseEvent event) throws IOException {
  	FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
  }

  @FXML
		public void goLocation(MouseEvent event) throws IOException {

				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#reminderBtn].onMouseClicked
			@FXML
			public void goReminder(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#exerciseBtn].onMouseClicked
			@FXML
			public void goExercise(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#homeBtn].onMouseClicked
			@FXML
			public void goHome(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/HomepageView.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#foodBtn].onMouseClicked
			@FXML
			public void goFood(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}
			// Event Listener on ImageView[#socialBtn].onMouseClicked
			@FXML
			public void goSocial(MouseEvent event) throws IOException {
				// TODO Autogenerated
				FXMLLoader loader=new FXMLLoader();
				loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
				 myScene=(Scene)((Node)event.getSource()).getScene();
				 Stage stage=(Stage)(myScene).getWindow();
				 Parent nextView=loader.load();
				 stage.setScene(new Scene(nextView));
				 stage.show();
			}

	// Event Listener on ImageView[#wholeMilk].onMouseClicked
	@FXML
	public void filterWholeMilk(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("WholeMilk")) {
				meatCategory.add(hasMeat.getName());
			}
		}	
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Whole milk");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Whole milk");

	}
	
	// Event Listener on ImageView[#iceCream].onMouseClicked
	@FXML
	public void filterIceCream(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("IceCream")) {
				meatCategory.add(hasMeat.getName());
			}
		}	
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Ice Cream");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Ice Cream");

	}
	
	
	// Event Listener on ImageView[#cheese].onMouseClicked
	@FXML
	public void filterCheese(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("Cheese")) {
				meatCategory.add(hasMeat.getName());
			}
		}	
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Cheese");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Cheese");
	}
	
	// Event Listener on Button[#viewMilk].onMouseClicked
	@FXML
	public void viewMilk(MouseEvent event) throws IOException {
	
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("MILK")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);
		fSRC.setSearchResult("Milk");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Milk");

	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		viewMilk.setStyle("-fx-border-color: #17202A; -fx-border-width: 3px;-fx-background-color:pink;");
	}
}
