package healthApp.controller;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import healthApp.data.FoodDB;
import healthApp.model.Food;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;


public class filteredBreadAndCerealController implements Initializable{
	@FXML
	private Button viewBreadAndCereal;
	@FXML
	private ImageView bread;
	@FXML
	private ImageView rice;
	@FXML
	private ImageView oat;
	@FXML
	private ImageView noodle;
	
	private Scene myScene;
	
	FoodDB foodDatabase = new FoodDB();

    @FXML
    private ImageView backBtn;
    @FXML
    private ImageView locationBtn;
    @FXML
	private ImageView reminderBtn;
	@FXML
	private ImageView exerciseBtn;
	@FXML
	private ImageView homeBtn;
	@FXML
	private ImageView foodBtn;
	@FXML
	private ImageView socialBtn;
   
	
	   @FXML
	    void goBack(MouseEvent event) throws IOException {

	    	FXMLLoader loader=new FXMLLoader();
			loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
			 myScene=(Scene)((Node)event.getSource()).getScene();
			 Stage stage=(Stage)(myScene).getWindow();
			 Parent nextView=loader.load();
			 stage.setScene(new Scene(nextView));
			 stage.show();
	    }
    
	@FXML
	public void goLocation(MouseEvent event) throws IOException {

		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	// Event Listener on ImageView[#reminderBtn].onMouseClicked
	@FXML
	public void goReminder(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	// Event Listener on ImageView[#exerciseBtn].onMouseClicked
	@FXML
	public void goExercise(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	// Event Listener on ImageView[#homeBtn].onMouseClicked
	@FXML
	public void goHome(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/HomepageView.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	// Event Listener on ImageView[#foodBtn].onMouseClicked
	@FXML
	public void goFood(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	// Event Listener on ImageView[#socialBtn].onMouseClicked
	@FXML
	public void goSocial(MouseEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
		 myScene=(Scene)((Node)event.getSource()).getScene();
		 Stage stage=(Stage)(myScene).getWindow();
		 Parent nextView=loader.load();
		 stage.setScene(new Scene(nextView));
		 stage.show();
	}
	
    /*
	// Event Listener on Button[#backBtn].onAction
		@FXML
		public void goBack(ActionEvent event) throws IOException {
			
			FXMLLoader loader=new FXMLLoader();
			loader.setLocation((getClass().getResource("/healthApp/view/NutritionTrackingHomepage.fxml")));
			 myScene=(Scene)((Node)event.getSource()).getScene();
			 Stage stage=(Stage)(myScene).getWindow();
			 Parent nextView=loader.load();
			 stage.setScene(new Scene(nextView));
			 stage.show();
		}
		*/
		
	// Event Listener on Button[#viewBreadAndCereal].onMouseClicked
	@FXML
	public void viewBreadAndCereal(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("BREADANDCEREAL")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Bread and cereal");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Bread and cereal");
}
	// Event Listener on ImageView[#bread].onMouseClicked
	@FXML
	public void filterBread(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("Bread")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Bread");
}
	// Event Listener on ImageView[#rice].onMouseClicked
	@FXML
	public void filterRice(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("Rice")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Rice");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Rice");
}
	// Event Listener on ImageView[#oat].onMouseClicked
	@FXML
	public void filterOat(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("Oat")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Oat");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Oat");
}
	// Event Listener on ImageView[#noodle].onMouseClicked
	@FXML
	public void filterNoodles(MouseEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader();
		loader.setLocation((getClass().getResource("/healthApp/view/filteredSearchResult.fxml")));
		myScene=(Scene)((Node)event.getSource()).getScene();
		Stage stage=(Stage)(myScene).getWindow();
		Parent nextView=loader.load();
		stage.setScene(new Scene(nextView));
		stage.show();
		ArrayList <Food> allFood = new ArrayList<Food>(foodDatabase.getMap().values());
		ArrayList <String> meatCategory = new ArrayList <String>();
		for (Food hasMeat : allFood) {
			if (hasMeat.getCategory().contains("Noodles")) {
				meatCategory.add(hasMeat.getName());
			}
			
			
		}
		filteredSearchResultController fSRC = loader.getController();
		fSRC.addToVbox(meatCategory);	
		fSRC.setSearchResult("Noodles");
		fSRC.setSearchResultX(meatCategory);
		fSRC.setInputFoodX("Noodles");
		
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		viewBreadAndCereal.setStyle("-fx-border-color: #17202A; -fx-border-width: 3px;-fx-background-color:pink;");
		
	}
}
