package healthApp.controller;

import java.io.IOException;
import java.net.URL;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.ResourceBundle;

import healthApp.data.EventDB;
import healthApp.model.Event;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Labeled;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class SocialFunctionController implements Initializable{
	@FXML
	private ImageView homePage;
	
	@FXML
	private Button mEventList;
	@FXML
	private Button aEventList;
	@FXML
	private Button cwEventList;
	@FXML
	private Button hEventList;
	@FXML
	private Button itEventList;
	@FXML
	private Button sEventList;
	@FXML
	private Button eEventList;
	
	private static String category;

	// Event Listener on ImageView[#homePage].onMouseClicked
	@FXML
	public void toHomePage(MouseEvent event) {
		// TODO Autogenerated
		try {
			Parent homePageLoader = FXMLLoader.load(getClass().getResource("/healthApp/view/HomepageView.fxml"));
			Scene homePageScene = new Scene(homePageLoader);
			
		
			Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
			window.setScene(homePageScene);
			window.show();
		}
		
		catch(IOException e) {
		}
	}
	
	public void toLocationPage(MouseEvent event) {
		try {
			Parent locationPageLoader = FXMLLoader.load(getClass().getResource("/healthApp/view/LocationView.fxml"));
			Scene locationPageScene = new Scene(locationPageLoader);
		
			Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
			window.setScene(locationPageScene);
			window.show();
		}
		
		catch(IOException e) {
		}
	}
	
	//Event Listener on Button[#mEventGeneration].onAction
	@FXML
	public void toEventList(ActionEvent event1) {
		try {
			SocialFunctionController.category = ((Labeled) event1.getTarget()).getText();
			EventDB db = new EventDB();
			
			ArrayList<Event> eventList = db.getAllEvents();
			
			LocalDateTime currentDateTime;
			
			for(Event e : eventList) {
				currentDateTime = LocalDateTime.now();
				
				if(e.getEventDateTime().isBefore(currentDateTime)) {
					db.deleteEvent(e.getName());
				}
			}
			Parent eventListLoader = FXMLLoader.load(getClass().getResource("healthApp/view/EventListView.fxml"));
			Scene eventListScene = new Scene(eventListLoader);
		
			Stage window = (Stage)((Node)event1.getSource()).getScene().getWindow();
			window.setScene(eventListScene);
			window.show();
		}
		catch(IOException e) {
		}
	}
	
	public static String getCategory() {
		return category;
	}
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
}
